### ISSUE TITLE
How to build kernel with patch ca0132.c

### ISSUE THREAD

**Issue by b10102016** [Conmanx360/QemuHDADump#4]
Hi Conmanx360

Sorry, because there's some problem during the Creative fourm's account activation, I can only contact you via opening an issue in this repo.

My name is Ian, I have used the patch from your [post](http://forums.creative.com/showthread.php?t=742256).

I have built  the kernel with the patch_ca0132.c, and boot up.
But there's some problem...

Please see the gist that is my kernel log dumped from `dmesg`

https://gist.github.com/b10102016/c5b8e68793d9bde8b88e2d449fd93bfb

You can notice that there are so many `PKCS#7 signature not signed with a trusted key` errors.
I believed that is my problem during building the ubuntu kernel, and here is the guide I followed to build the kernel.

https://askubuntu.com/questions/775609/how-to-compile-ubuntu-16-04-kernel-with-zfs-module

It generated a unsigned kernel. I thought that's the problem.

So could you teach me how to build a kernel?

My ubuntu version is 18.04 and the kernel I'm trying to build is 4.15.0-22-generic

you can get the kernel source from 
`git clone git://kernel.ubuntu.com/ubuntu//ubuntu-bionic.git`

**Comment by ghost** [comment]
You will have to sign the module:
https://www.kernel.org/doc/html/v4.15/admin-guide/module-signing.html
https://blog.ubuntu.com/2017/08/11/how-to-sign-things-for-secure-boot

Also you can learn how to build the kernel on ubuntu here:
https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel
https://help.ubuntu.com/community/Kernel/Compile

I'm not using ubuntu, so I can't help you more than pointing you to the documentation.

btw. the patch should get into kernel 4.18.0 (if not 4.17.0).

**Comment by b10102016** [comment]
@mceier Thanks for replying,~ I'll try it next weekend.

**Comment by b10102016** [comment]
@mceier Finally, I got it to work. The problem above may cause from wrong version of kernel.

Here is the kernel I used to test the driver. 
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.17-rc6/

but sadly, After booting in to OS, I still can't get it to  work...

So now, How can I help you to debug?

**Comment by b10102016** [comment]
I get it to work after a full shutdown.~~

I still can help you to debug, but I totally have no idea where to begin...

**Comment by Conmanx360** [comment]
So does it work or not?

**Comment by b10102016** [comment]
@Conmanx360  Yes, the driver from your post. 
I can help you to collect the shutdown sequence, but I dont know where to start

**Comment by Conmanx360** [comment]
What card do you have? In the post, I talk about using the hda-verb to check it. Do that and let me know if you could.

**Comment by Conmanx360** [comment]
Also, it'd be more quick if we correspond over email if you wouldn't mind. conmanx360@gmail.com is my email.
